package org.apmem.widget.notes;


public class Constants {
    public static final String INTENT_EXTRA_WIDGET_ITEM_ID = "INTENT_EXTRA_WIDGET_ITEM_ID";
	public static final String ACTION_WIDGET_UPDATE_FROM_ACTIVITY = "ACTION_WIDGET_UPDATE_FROM_ACTIVITY";
	public static final String ACTION_WIDGET_UPDATE_FROM_WIDGET_READY_ITEM = "ACTION_WIDGET_UPDATE_FROM_WIDGET_READY_ITEM";
	public static final String ACTION_WIDGET_UPDATE_FROM_WIDGET_NEXT = "ACTION_WIDGET_UPDATE_FROM_WIDGET_NEXT";
	public static final String ACTION_WIDGET_UPDATE_FROM_WIDGET_PREV = "ACTION_WIDGET_UPDATE_FROM_WIDGET_PREV";
}
